service:
- docker

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - bash
    - unzip
    - curl
    - jq
    - libxml2-utils
    - docker-ce
    - python-pip

install: true
before_script:
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8443 8080 80

script:
- ./gradlew >/dev/null
- java -jar ./build/libs/*.jar &
- wait_for 8443
- curl -k https://127.0.0.1:8443
- stop_any 8443
#
- bash ./build/libs/*.jar &
- wait_for 8443
- curl -k https://127.0.0.1:8443
- stop_any 8443
#
- ./gradlew composeDown
- ./gradlew composeUp
- curl -k https://127.0.0.1:8443
- ./gradlew composeDown
#
- ./mvnw >/dev/null
- java -jar ./target/*.jar &
- wait_for 8443
- curl -k https://127.0.0.1:8443
- stop_any 8443
#
- bash ./target/*.jar &
- wait_for 8443
- curl -k https://127.0.0.1:8443
- stop_any 8443
#
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down -P docker
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up -P docker
- sleep 20
- curl -k https://127.0.0.1:8443
- ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down -P docker

before_deploy: ./gradlew documentation

env:
  global:
  - TERM=dumb
  - secure: FADxRs3aTK43Alas7fKjSPsMe9ZO/ra1ju8e1M8WoVHcCEC9Cq0mCCvk4Q/goGt3C+0JIC6+FAT45h+QOYpqhXupVgkeyu9rirTBdkk+/Q986agyin6DrPjg9SSQOKoNs/nonp5oqemWWjyZviQq1bCvW7duWqq8obzn1qf/RrhoJm5Ls3QwOf0+T1Z7Etr0/89y7nOecOrQ/v0cYth/Z63NNmAki9fysvNwLaHx3Y+kDtDzZdgXqPpDHLG6nA1ip3Ht1WFqSdnY9Gxu5HGoXP/xkZ1Z+VnnfM/PdoaM7s+ztafVXuHzHX59/KyIDqkWNbmY8G4/e6XIr9srGJdUBmPcC8hAaV9jFdCk3QmzQDGF7GGlZcWnPUltw+T+fsu7golmLkOato3PFIq65qOiwdRAUvoeD7iu4XILWG1B5h0P6bYmIBqd5AGXU+6/R7VxO7707Qvl3K9KL5aUS8Xt/KtqStlu6wW4sYBH1hAz2ssliRc9CpV0sMjhRuHaJ6QX+ckZaQAf6MIyPzMPlpJausMn8UuJH8YBnjtxuVz0uLIVjgxveYFGuErYtpwA12E60yHT35BFXBVB2halzzRLSCt/W92/RIBmkDkkhLvIX+sAWiBERN04hX2Xz+FpcPZGCTWCSFdqhNmK/0uVTVxTfcd/L7GHzow1xvulFs80giw=

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

before_cache:
- sudo rm -rf $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
