version: '2.1'

services:

  gradle-spring-boot-http2-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ['gradle-spring-boot-http2-app-data:/home/appuser']
    ports: ['8443:8443']
    restart: unless-stopped
    networks:
      public-net:
        aliases:
        - app

volumes:
  gradle-spring-boot-http2-app-data:

networks:
  public-net:
    driver: bridge
